name: "Marquis RS Interface"
description: "Custom ESPHome component for Marquis Spa Recreational Series (e.g., Quest RS, Destiny RS, Reward RS, ca. 2000+)"
files:
  - marquis_rs_interface.cpp
  - marquis_rs_interface.h
includes:
  - marquis_rs_interface.h
classes:
  - namespace: esphome
    class: MarquisRSInterface
yaml:
  name: marquis_rs_interface
  required: true
  fields:
    - name: id
      type: string
      required: false
      description: ID for the component instance.
    - name: clock_pin
      type: gpio
      required: true
      description: GPIO pin connected to the LCD clock signal.
    - name: data_pin
      type: gpio
      required: true
      description: GPIO pin connected to the LCD data signal.
